spring.datasource.url=jdbc:postgresql://db:5432/kingdomrpg
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=kingdom
spring.datasource.password=kingdom
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
