package t1tanic.kingdomrpg.engine;

import io.micrometer.core.instrument.MeterRegistry;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import t1tanic.kingdomrpg.domain.character.Player;
import t1tanic.kingdomrpg.engine.commands.*;

import java.util.Arrays;

/**
 * Parses user text inputs, resolves command shortcuts, and dispatches them to specialized action handlers.
 * <p>The {@code CommandParser} handles text normalization (trimming, casing, whitespace splitting), handles core
 * directional or shorthand routing (e.g., mapping "n" to a north move array), and measures command performance
 * using a Micrometer {@link MeterRegistry} timer metric.</p>
 *
 * @author t1tanic
 * @version 1.0
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class CommandParser {

    private final LookCommand      lookCommand;
    private final GoCommand        goCommand;
    private final TakeCommand      takeCommand;
    private final DropCommand      dropCommand;
    private final InventoryCommand inventoryCommand;
    private final StatusCommand    statusCommand;
    private final SpellsCommand     spellsCommand;
    private final CastCommand       castCommand;
    private final RollCommand       rollCommand;
    private final AbilitiesCommand  abilitiesCommand;
    private final AttemptCommand    attemptCommand;
    private final HelpCommand       helpCommand;
    private final SearchCommand     searchCommand;
    private final MeterRegistry    meterRegistry;

    /**
     * Tokenizes a raw user string input and executes the associated command within a monitored timer scope.
     * <p>If the input consists only of whitespace or is null, a short interactive help fallback reminder is returned.
     * Otherwise, the string is split by spaces into a command verb and trailing operational arguments.</p>
     *
     * @param player the active player entity executing the text command
     * @param input  the raw textual command line payload sent from the player interface
     * @return the result text string generated by the matching command execution flow
     */
    public String parse(Player player, String input) {
        if (input == null || input.isBlank()) {
            return "Hm? (type 'help' for commands)";
        }

        String[] parts = input.trim().toLowerCase().split("\\s+");
        String   verb  = parts[0];
        String[] args  = Arrays.copyOfRange(parts, 1, parts.length);

        log.debug("Dispatching '{}'", verb);
        return meterRegistry.timer("game.command.duration", "verb", verb)
                            .record(() -> dispatch(player, verb, args));
    }

    /**
     * Maps normalized string verbs and aliases to their respective engine implementation instances.
     * Handles contextual shortcuts for directions (e.g., "north" or "n") and standard synonym patterns
     * (e.g., "get" and "pick" routing to {@link TakeCommand}).
     *
     * @param player the active player entity context reference
     * @param verb   the normalized, lowercase action keyword being evaluated
     * @param args   the clean argument tokens following the command keyword
     * @return a text description outcome mapping to user interface console views
     */
    private String dispatch(Player player, String verb, String[] args) {
        return switch (verb) {
            case "look", "l"                         -> lookCommand.execute(player, args);
            case "go", "move"                        -> goCommand.execute(player, args);
            case "north", "n"                        -> goCommand.execute(player, new String[]{"north"});
            case "south", "s"                        -> goCommand.execute(player, new String[]{"south"});
            case "east",  "e"                        -> goCommand.execute(player, new String[]{"east"});
            case "west",  "w"                        -> goCommand.execute(player, new String[]{"west"});
            case "take", "get", "pick"               -> takeCommand.execute(player, args);
            case "drop"                              -> dropCommand.execute(player, args);
            case "inventory", "inv", "i"             -> inventoryCommand.execute(player, args);
            case "status", "stats"                   -> statusCommand.execute(player, args);
            case "spells", "cantrips", "grimoire"    -> spellsCommand.execute(player, args);
            case "cast", "use"                       -> castCommand.execute(player, args);
            case "roll"                              -> rollCommand.execute(player, args);
            case "abilities", "ability", "hab"       -> abilitiesCommand.execute(player, args);
            case "attempt", "try"                    -> attemptCommand.execute(player, args);
            case "search", "examine", "inspect"      -> searchCommand.execute(player, args);
            case "help", "?"                         -> helpCommand.execute(player, args);
            default -> "I don't understand '" + verb + "'. Type 'help' for commands.";
        };
    }
}
